In [13]:
import pandas as pd
import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report, accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split

In [15]:
df = pd.read_csv('spam.csv', encoding='latin1')
df = df[['v1', 'v2']]
df.columns = ['Target', 'Email']
df.head()

  Target                                              Email
0    ham  Go until jurong point, crazy.. Available only ...
1    ham                      Ok lar... Joking wif u oni...
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
3    ham  U dun say so early hor... U c already then say...
4    ham  Nah I don't think he goes to usf, he lives aro...

In [17]:
X_train, X_test, y_train, y_test = train_test_split(df['Email'], df['Target'], test_size=0.2, random_state=42, stratify = df['Target'])

In [19]:
vector = TfidfVectorizer(stop_words='english')
X_train_tfidf = vector.fit_transform(X_train)
X_test_tfidf = vector.transform(X_test)

# Train the model

In [22]:
model = LogisticRegression()

In [26]:
model.fit(X_train_tfidf, y_train)

LogisticRegression()

In [28]:
predictions = model.predict(X_test_tfidf)

In [30]:
print("Accuracy Score: ", accuracy_score(y_test, predictions))
print(classification_report(y_test, predictions))

Accuracy Score:  0.967713004484305
              precision    recall  f1-score   support

         ham       0.96      1.00      0.98       966
        spam       1.00      0.76      0.86       149

    accuracy                           0.97      1115
   macro avg       0.98      0.88      0.92      1115
weighted avg       0.97      0.97      0.97      1115

In [48]:
mesage = ['Congrations! Claim your free prize today']
mesage_vect = vector.transform(mesage)
prediction = model.predict(mesage_vect)

In [50]:
print(prediction)

['spam']

# Find important spam words

In [62]:
feature_names = vector.get_feature_names_out()
coefficients = model.coef_[0]

# Create a dataframe

In [65]:
importance = pd.DataFrame({
    'Word': feature_names,
    'Weight': coefficients
})

# Most spam indicating words

In [69]:
importance.sort_values(
    by='Weight',
    ascending = False 
).head(20)

         Word    Weight
6821      txt  4.785611
1763    claim  3.605844
6848       uk  3.532644
4374   mobile  3.428065
7327      www  3.379593
6256     stop  3.264580
5809  service  3.232546
5501    reply  3.084886
2873     free  2.965502
303      150p  2.959828
6545     text  2.791914
5214    prize  2.567959
6922   urgent  2.537688
529        50  2.529480
7264      won  2.490050
1843      com  2.316099
7212      win  2.285622
4574      new  2.193538
1619     cash  2.185678
319        18  2.062699